---
- name: ensure Git is installed via the system package
  apt: name=git-core state=present update_cache=yes
  become: true


- name: create deploy key directory if it does not exist
  file: path=/home/{{ deploy_user }}/deploy_key state=directory
  become: true


- name: ensure deploy key is on remote server
  copy: src={{ local_deploy_key_dir }}/deploy_key
        dest=/home/{{ deploy_user }}/deploy_key/deploy_key
        mode=0600 owner={{ deploy_user }} group={{ deploy_group }}
  become: true


- name: clone or pull latest web app code
  git: repo={{ code_repository }} dest={{ app_dir }}
       key_file=/home/{{ deploy_user }}/deploy_key/deploy_key
       accept_hostkey=yes
  become: true
